### ISSUE TITLE
Add alternative to http://s2.sidewalklabs.com/regioncoverer/

### ISSUE THREAD

**Issue by igorgatis** [aaliddell/s2cell#14]
The http://s2.sidewalklabs.com/regioncoverer/ has been down for a while now. You may want to add the following links to the list of visualizations:

* https://s2.inair.space/ whose related post worth mentioning https://blog.nobugware.com/post/2018/wasm_go_s2_javascript/

* https://igorgatis.github.io/ws2/ -my fork from the link above which has some of the functionality that sidewalklabs' provided.

**Comment by aaliddell** [comment]
Thanks, the first of those new links also now appears to be dead too. Oh the irony when their blog post is sad about the original being down :laughing:

I'll replace both the sidewalklabs with your fork then.
